export type ColumnsNames =
  | 'New Submission'
  | 'Qualified for Interview'
  | 'Interview scheduled'
  | 'Interview completed'
  | 'Approved for Hire'
  | 'Offer Accepted'
  | 'Hired'
  | 'Rejected by Hiring Team'
  | 'Ghosted by Candidate'
  | 'Runner-ups'
  | 'Submitted to ATS'
  | 'ATS Transmission Failed'
  | 'Interview'
  | 'Phone Screen'
  | 'Technical Test'
  | 'Assessment'
  | 'Offer'
  | 'Sourced'
  | 'Applied'
  | 'Bebra Hired'
  | 'Invited to gay party'
  | 'Invite to QMALL'
  | 'KICK FROM GAY PARTY'
  | 'New Invite to gay party'
  | 'q'
  | 'w'
  | 'r'
  | 'qwe'
  | 'BebraW'
  | '2qweqwe'
  | 'zxcasd'
  | 'qweqsdadsad'
  | 'asdqweqwe'
  | 'qweqwe1234qsfac'
  | 'НЮХАЧ ПОП';
